#! /bin/sh

#
# do_header
#
# Script para actualizar las cabeceras automáticamente cuando sea necesario.
#
# $Id$
#

tmp_header="header$$.tmp"

for file in `find . -path '*CVS' -prune -o -type f -printf "%P "`; do
	
	test -r $file -a -w $file || continue
	case "$file" in
		.*|*.[oO]|do_header|template.*) continue ;;
		*.[cChH]) template_file="template.h" ;;
		Makefile) template_file="template.hash" ;;
		       *) template_file="template.plain" 
		          test -f $template_file || \
			  sed -e 's/^#//' template.hash >$template_file ;;
	esac

	sed -n -e '0,/^[ 	]*$/p' $file >$tmp_header
	
	if diff $tmp_header $template_file >/dev/null 2>&1; then
		# Cabeceras iguales 
		echo "Fichero $file no necestia actualización."
	else
		# Cabeceras distintas. Reemplazar
		tfile="$file.s"
		echo "Actualizando $file."
		sed -e '0,/^[ 	]*$/d' $file >$tfile
		cat $template_file $tfile >$file
		rm $tfile
	fi
	
done

rm -f template.plain $tmp_header
